from datetime import datetime, timezone
from sqlmodel import SQLModel, Field
from typing import Optional

class ChatSession(SQLModel, table=True):
    """
    Database table storing chat sessions/threads created by administrators.
    """
    id: Optional[int] = Field(default=None, primary_key=True)
    title: str = Field(index=True, nullable=False)
    user_id: int = Field(foreign_key="user.id", nullable=False)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        nullable=False
    )

class ChatMessage(SQLModel, table=True):
    """
    Database table storing the historical messages for chat sessions.
    """
    id: Optional[int] = Field(default=None, primary_key=True)
    session_id: int = Field(foreign_key="chatsession.id", nullable=False)
    
    # Either "user" or "ai"
    sender: str = Field(index=True, nullable=False)
    content: str = Field(nullable=False)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        nullable=False
    )

class AgentAction(SQLModel, table=True):
    """
    Database table storing target server execution requests generated by the AI
    which require human-in-the-loop validation/approval before being executed.
    """
    # UUID string to make the action approval identifier secure and unguessable
    id: str = Field(primary_key=True)
    session_id: int = Field(foreign_key="chatsession.id", nullable=False)
    server_id: int = Field(foreign_key="server.id", nullable=False)
    command: str = Field(nullable=False)
    
    # Status can be: "pending", "approved", or "rejected"
    status: str = Field(default="pending", index=True, nullable=False)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        nullable=False
    )
